### ISSUE TITLE
Resource amount validation isn't retrigger on account balance updates

### ISSUE THREAD

**Issue by mpetrunic** [sygmaprotocol/sygma-widget#100]
## Expected Behavior
Once you connect wallet and update balance,amount input should be validated again

## Current Behavior
validation message stays even though it's valid value

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Version

Sygma commit (or docker tag):
sygma-solidity version:
sygma-substrate version:
Go version:

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/100?planning-poker) with Zenhub @Lykhoyda @mpetrunic @wainola
