### ISSUE TITLE
Preselect destination wallet to be connected wallet

### ISSUE THREAD

**Issue by mpetrunic** [sygmaprotocol/sygma-widget#102]
## Implementation details

When transferring between same type of network, we should autoinput connected wallet address as destination address.

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/102?planning-poker) with Zenhub @Lykhoyda @mpetrunic @wainola
