### ISSUE TITLE
Create examples for the widget

### ISSUE THREAD

**Issue by wainola** [sygmaprotocol/sygma-widget#11]
We should have examples to showcase usage of the widget in different frameworks

## Implementation details

- create `vue` example implementing the widget
- create `vanilla js` example
- create `lit` example
- create `angular` example

## Testing details

- test that examples are able to work on development mode and build successfully

## Acceptance Criteria

- examples render customized version of the widget

**Comment by MakMuftic** [comment]
Finished during initial widget release.
