### ISSUE TITLE
Ability to "Start new transfer" is not working

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-widget#110]
Severity: High | Priority: High

**Context**: Use a valid flow for E2E transfer on widget version 0.1.0 (2024-02-22) is not working. 

**STR**:
1. Select from "Sepolia" and destination "Mumbai".
2. Connect to metmask wallet and select ERC20LRTest token.
3. Fill in 5 tokens and select approve spending.
4. Transfer tokens. 
5. Select "Start new transfer" from the last screen.

**Exp**: The user to be redirected to the start transfer screen (similar to the first interaction)
**Act**: Nothing happens when pressing "Start new transfer"

**Comment by wainola** [comment]
@LyonSsS I thought solutio to this involved more complex approach but it looks like it was very straightforward. In the PR you can check the deployed url. Remember to use preview.

**Comment by LyonSsS** [comment]
Verified on PR branch - > https://github.com/sygmaprotocol/sygma-widget/pull/126 
Issue is fixed now
