### ISSUE TITLE
Reset context when disconnecting/lock wallet

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-widget#113]
Severity: low | Priority: low

**Note**: After connecting Metamask wallet, and setting everything ready for a transfer, if the user disconnects the wallet via disconnect or lock ( metamask option), the context is not reseted. 

![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/db7ad5cc-4484-4fdb-b59b-8e3b4726efae)

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/113?planning-poker) with Zenhub @Lykhoyda @mpetrunic @wainola

**Comment by mpetrunic** [comment]
@LyonSsS @MakMuftic Do we wanna reset everything? maybe we should just reset balance and amount?

**Comment by LyonSsS** [comment]
This is again a business decision. 
It would keep only source and destination ... but I would reset token type, amount and balance ... as if reconnect a new wallet & we have multiple tokens type mapping in the future for the same (source - destination mix) ... then we should let the user reselect the same token type, or another one ... and only load balance once. If I reconnect another wallet but I want to change the token type, we try to  read balance for 2 token types. 
CC: @itsbobbyzzz168

**Comment by itsbobbyzzz168** [comment]
Yep, sorry, i think @wainola already implemented this (correct me if i'm wrong @LyonSsS @wainola )? Just laying our Liviu's suggestion for clarity:

If wallet disconnected, reset; 
- token type
- amount
- balance

If new wallet connected, reset:
- amount
- balance

**Comment by LyonSsS** [comment]
Tested on release version - It behaves fine except that we agree not to reset source and destination. We only agree to reset token type, amount and balance. 
![Lock_wallet_orDisconnect](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/76ca426c-b75a-4ed3-822f-88ff36c689e8)

**Comment by mpetrunic** [comment]
@LyonSsS There is explanation in the PR:
```
The original issue, mentions NOT clear the selected and destination network. But we fetch the resource data and other data on selecting the destination network, so to avoid unclear behavior for the user to click again the destination network I clear all the data. If it's important to have the behavior to keep the state of networks, it would be better to keep at least a selected network and a clear destination network to avoid potential bugs with the data being not updated on component levels. IMO clearing the entire state is the most bulletproof way to avoid previous selected data
```

@itsbobbyzzz168 I would keep it like this (reset all for now) and maybe open feature req issue if we wanna handle that in the future as it introduces a lot of edge cases 🤷🏻‍♂️

**Comment by Lykhoyda** [comment]
@LyonSsS The current expected behavior is that after the transfer is complete, all the fields except the source network will be cleared. The changes were done in the PR https://github.com/sygmaprotocol/sygma-widget/pull/163/files

**Comment by LyonSsS** [comment]
Bases on the the last meeting we do agree to reset all. 
Closing this issue
