### ISSUE TITLE
Switching to a different TOKEN mapping for "From - TO" relationship is not updated in UI if amount is inserted

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-widget#117]
Severity: Low | Priority: Medium

**Context**: When switching to another "From - To" mapping, that needs to update the available compatible ERC20 token vs previous selection, UI is not updated. 

**STR**:
1. Login with metmask and select from as Sepolia.
2. Select to as Mumbai and select drop down to ERC20RLTest tokens.
3. After balance is updated, insert an amount <= MAX in the "Amount to transfer" field. 
4. Select TO destination to Rhala, which has the only mapping to ERC20 token sygUSDC. 

**Exp**: UI to update the correct erc20 mapping.
**ACT**: Nothing happened. The same ERC20RLTest token remain. 

![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/aff1c17b-d907-4fdd-ac26-7e26252f19dd)

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/117?planning-poker) with Zenhub @Lykhoyda @mpetrunic @wainola

**Comment by saadjhk** [comment]
@LyonSsS I tested this functionality by pulling latest commits from `main` and it seems to be fixed, can you please validate the functionality once?

**Comment by LyonSsS** [comment]
I did retested it on latest build from https://github.com/sygmaprotocol/sygma-widget/pull/60 and I could reproduce it. 
![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/045b1b2b-032c-415f-8702-af31ac6fede0)

**Comment by LyonSsS** [comment]
Retested on CoreReleaseBranch - this now works fine
