### ISSUE TITLE
Refresh MAX and Amount to transfer field when changing Source

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-widget#118]
Severity: Low | Priority: Low

**Context**: After selecting a relationship Source-Dest and filling in some "Amount to transfer", if the user then switches to another source, the context of Max and Amount to transfer is not refreshed. 

**STR**:
1. Select From  as "Mumbai" and connect metmask wallet to the correct network.
2. Select To as "Sepolia" and then select ERC20RLTest token.
3. After balance is updated, input an amount <= Max value for the "Amount to transfer" field.
4. Change From value now to "Cronos".

**Exp**: The context to be resseted for the token type to be transferred, max amount, and amount to be transferred. 
**Act**: The only context that is resseted is for the token type. 
![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/718a44d5-8a6f-497f-81b2-f652a26ade6c)

**Comment by wainola** [comment]
this issue is related to #111

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/118?planning-poker) with Zenhub @Lykhoyda @mpetrunic @wainola

**Comment by LyonSsS** [comment]
Tested based on fix https://github.com/sygmaprotocol/sygma-widget/pull/127 
The "Amount to transfer", still persist
<img width="848" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekd3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--25a200042fe8d29d47366daff5b51fdb4fe37cdb/Amount_To_Transfer.gif" alt="Amount_To_Transfer.gif" />

**Comment by LyonSsS** [comment]
Retested on https://github.com/sygmaprotocol/sygma-widget/pull/127 - the amount issue still persists

**Comment by LyonSsS** [comment]
retested and fixed https://github.com/sygmaprotocol/sygma-widget/pull/127
