### ISSUE TITLE
Allow incompatible routes to be selected from UI

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-widget#119]
Severity: Medium | Priority: Medium
**Context**:  After switching to a From network that allows multiple To destinations, then the User can select an incompatible From - To mix. 

**STR**:
1. Select From network as "Sepolia"
2. Select To destination as "Mumbai"
3. Select From network as "Cronos" 

**Exp**: The To destination to be updated only to "Sepolia" as compatible match.
**Act**: The To destination were not updated to match the correct route. 

![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/9200777b-1c5f-4dce-81fd-b804fa7c97a8)

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/119?planning-poker) with Zenhub @Lykhoyda @mpetrunic @wainola

**Comment by wainola** [comment]
I think this issue could be linked to #112. CC: @MakMuftic @mpetrunic

**Comment by LyonSsS** [comment]
Fixed with https://github.com/sygmaprotocol/sygma-widget/pull/127

**Comment by LyonSsS** [comment]
Retested - fixed with https://github.com/sygmaprotocol/sygma-widget/pull/127
