### ISSUE TITLE
If a flow reaches the end of a transfer, disconnecting and reconnecting the wallet will keep the context

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-widget#120]
Severity: Low | Priority : Medium

**Context**:  After a user does a transfer flow and reaches the end page, if he disconnects the metamask wallet, the UI will reset to home page, but will reach back to the finished transfer page if he reconnects the same wallet. 
![Disconnect_Reconnect](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/388c6646-202f-4b24-bb64-1886652005ba)

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/120?planning-poker) with Zenhub @Lykhoyda @mpetrunic @wainola
