### ISSUE TITLE
First time allow spending from Mumbai is broken

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-widget#122]
**Note**: When we connect with new context to widget and select Mumbai as From, when the time comes to select "Allow Spending", first time is requested for a broken value. 

![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/cee44161-beac-4d15-993f-a9e4184dc21a)

**Comment by mpetrunic** [comment]
@LyonSsS This is not an issue. This is indeed fee amount set for this token on Mumbai as you can see from transfer: https://scan.test.buildwithsygma.com/transfer/0x6173e21499ae039b208912d0f49e876af50814882c02ea708f395405baa1ab13

It will be a lot clearer once we implement #55
