### ISSUE TITLE
Metamask not prompting network switch when user doesn't have network in metamask

### ISSUE THREAD

**Issue by mpetrunic** [sygmaprotocol/sygma-widget#132]
## Expected Behavior

We should first request metamask to add a network using network details from chainlist.org and then prompt switching network

## Current Behavior

Nothing happens

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Version

Sygma commit (or docker tag):
sygma-solidity version:
sygma-substrate version:
Go version:

**Comment by LyonSsS** [comment]
This is a valid bug which I did not tested. 
Expected behavior described in this issue is the perfect way to do it.

**Comment by LyonSsS** [comment]
<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLy9EQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b243e4ea3f94d0ce5a84005d1e97feabfe9c9d02/image.png" alt="image.png" />
