### ISSUE TITLE
Can I test this widget without running any nodes locally?

### ISSUE THREAD

**Issue by chipset10** [sygmaprotocol/sygma-widget#140]
When I try 'connect wallet' , I see this error whatever network I select.

![image](https://github.com/sygmaprotocol/sygma-widget/assets/16154269/cf1637a1-fe02-4bed-bfc3-aa2b161bdd2c)

Is it impossible to test this widget without running any nodes locally?

**Comment by wainola** [comment]
hi, thanks for your question. You don't need any local setup to run the widget, once you cloned and install all the dependencies you can run the widget and connect your wallet to the testnets our bridge support.

**Comment by chipset10** [comment]
I will test again. Thanks for your kind answer @wainola .
