### ISSUE TITLE
Enable whitelisting resources

### ISSUE THREAD

**Issue by mpetrunic** [sygmaprotocol/sygma-widget#148]
## Implementation details

Make sure if user passed whitelistedSourceResources property that we filter available resources to only allow those. Property should probably changed to accept some identifier and not entire resource object.

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/148?planning-poker) with Zenhub @Lykhoyda @mpetrunic @saadjhk @wainola

**Comment by LyonSsS** [comment]
Tested on https://github.com/sygmaprotocol/sygma-widget/pull/170 and it passed
