### ISSUE TITLE
Display amount on destination

### ISSUE THREAD

**Issue by mpetrunic** [sygmaprotocol/sygma-widget#156]
## Implementation details
In addition to fee, we should also display how much tokens will user receive on destination.

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/156?planning-poker) with Zenhub @Lykhoyda @mpetrunic @saadjhk @wainola
