### ISSUE TITLE
Display gas fee estimation

### ISSUE THREAD

**Issue by mpetrunic** [sygmaprotocol/sygma-widget#157]
depends on #153 

## Implementation details

In addition to fee, we should display estimation on how much gas (in native currency) + dollar value should transfer cost

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/157?planning-poker) with Zenhub @saadjhk @wainola @mpetrunic @Lykhoyda

**Comment by saadjhk** [comment]
@mpetrunic @MakMuftic I'd like to know what service provider are we going to use in order to show value in fiat

**Comment by mpetrunic** [comment]
value in fiat is blocked by #153

**Comment by saadjhk** [comment]
@mpetrunic I went through the sdk and I see that there isn't any method that provides estimation of the contract call, I will believe we should add it there first?

**Comment by mpetrunic** [comment]
> @mpetrunic I went through the sdk and I see that there isn't any method that provides estimation of the contract call, I will believe we should add it there first?

But in the widget you have transaction(+approvals) that will be executed, just can use ethers to estimate.

**Comment by saadjhk** [comment]
@mpetrunic so the flow should show estimation for each transaction (including all approvals)?

**Comment by mpetrunic** [comment]
> @mpetrunic so the flow should show estimation for each transaction (including all approvals)?

Well approvals are also cost of transfer 😅

**Comment by LyonSsS** [comment]
<img width="564" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVBFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0d771675c82a0b3ba7edf3ca5ddd113d6631f16/image.png" alt="image.png" />
All without the dollar value ( which is currently blocked)
