### ISSUE TITLE
Cronos maps Sepolia destination more than once

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-widget#166]
Severity: Low | Priority: Medium

When choosing Cronos as a source, to transfer to another destination, the user sees multiple Sepolia destinations. 
![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/8acc28fe-f22a-46a5-b6eb-9c5f9d325bc9)

## Expected Behavior

To see only 1 Sepolia available

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Version

Sygma commit (or docker tag):
sygma-solidity version:
sygma-substrate version:
Go version:

**Comment by Lykhoyda** [comment]
@LyonSsS The issue is not reproducible anymore, please double-check

**Comment by LyonSsS** [comment]
Retested and closed
