### ISSUE TITLE
Create network dropdown selectors

### ISSUE THREAD

**Issue by wainola** [sygmaprotocol/sygma-widget#18]
We need to create the dropdown network selectors according to design.

## Implementation details

- render of the network list is dependable on the shared config - or our supported networks-.
- component receives reactive property from parent that will handle the state changes
- component should have property that display the default home network if wallet is connected
- follow style defined in figma

## Acceptance Criteria

- component should display a dropdown with options and be able to display the selected one

**Comment by itsbobbyzzz168** [comment]
@wainola checking if this can be closed off

**Comment by wainola** [comment]
> @wainola checking if this can be closed off

no, there is a current PR on draft that is going to be updated now that we have `sdk-manager` published. Will resume work on this now.
