### ISSUE TITLE
Networks added from chainlist.io miss block explorer parameter

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-widget#187]
**Context**:  When a user switches the widget to a Metamask missing network, then Metamask will bring up a pop-up to add the network with data provided from chainlist.io. Currently, the Block Explorer URL parameter is missing 

![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/2df6849d-f6c4-4f89-bc20-08f848844f23)
<img width="1469" 
![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/efded4e6-8cf6-4ab7-add8-db346417dc5e)

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/187?planning-poker) with Zenhub @saadjhk @wainola

**Comment by LyonSsS** [comment]
Tested on PR https://github.com/sygmaprotocol/sygma-widget/pull/200 - and it passed
