### ISSUE TITLE
Token drop down field, display the drop down icon over the token name

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-widget#188]
**Context**:  When selecting a token that has a longer name from the token drop down, the "arrow down" icon, that suggests a drop down field, overly with the name of the token. 

![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/2eb4b7bb-abdd-455b-9f37-8cb42cd094cd)

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/188?planning-poker) with Zenhub @saadjhk @wainola

**Comment by LyonSsS** [comment]
This is now fixed via https://github.com/sygmaprotocol/sygma-widget/pull/201
![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/63651baa-64b7-43cf-b463-01e012bf0778)
