### ISSUE TITLE
Create Amount to Transfer component

### ISSUE THREAD

**Issue by wainola** [sygmaprotocol/sygma-widget#19]
## Implementation details

- component should display both value or amount to tranfer and dropdown selector with the tokens available to select
- token list depends of resources per network defined in the shared config

To define:
- display transaction fee
- display price impact
- display amount to receive on destination network

## Acceptance Criteria

- upon token selection, user is able to select amount to transfer

**Comment by wainola** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/19?planning-poker) with Zenhub @FSM1 @wainola

**Comment by itsbobbyzzz168** [comment]
@wainola checking if this can be closed off

**Comment by wainola** [comment]
> @wainola checking if this can be closed off

@itsbobbyzzz168 no, there is a current PR on draft mode that needs to be updated now that we have `sdk-manager` published. Will resume work on this now.
