### ISSUE TITLE
Gas Fee estimation behavior, is not consistent for the actual transfer TX

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-widget#190]
**Context**: When a user transfers a token from one Chain to another, there is a 2 step process, where he signs for allow spending and then for the actual token transfer tx. The widget does not apply the same logic for the Gass Fee estimation behavior when we reach the transfer TX. 

![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/633e8463-55a8-45d5-aacb-c960bdf83e5e)

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/190?planning-poker) with Zenhub @saadjhk @wainola
