### ISSUE TITLE
Default token behavior is not working

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-widget#191]
**Context**:  When a user selects a specific "Source  - Destination" valid option, and connects the wallet, then the widget should display the value of the default Token Type selected in UI, if the wallet has funds on that specific source. Currently, this it is not happening, and the user is required to RE Select the same token type from the drop down. 

**STR**:
1. Connect an EVM wallet with SygUSDC funds on Sepolia and select source Sepolia. 
2. Select for the "To" field "Base_sepolia" 

Exp: The amount of available SygUSDC to be displayed by the widget in UI.
Act: There is no update of the amount of the SygUSDC token on Source, until the user RE SELECTS the same token type from the drop down. 
![Token_Ammount](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/84c953b8-22ad-4b2c-9f46-b52b1d53b24a)

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/191?planning-poker) with Zenhub @saadjhk @wainola

**Comment by wainola** [comment]
@LyonSsS what's the expectec behavior here if the route has more than one resource to be selected? Should the dropdown list have a default label like `select your token` even if the route has one resource to be selected?

**Comment by LyonSsS** [comment]
I am more inclined to this approach "select your token" than involving more logic behavior for the balance to be loaded as a default token. 
Currently there is a "default token" behavior (only UI) but with no logic behind it. 
What should we choose to do here @itsbobbyzzz168  ?

**Comment by itsbobbyzzz168** [comment]
Yep agreed, as in the stream sync let's re-label it to 'Select token' @LyonSsS @wainola
