### ISSUE TITLE
Amount to receive is not correct displayed when using the percentage fee handler 

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-widget#192]
**STR**: 
1.  Select source as Sepolia.
2. Select "TO" as Base_Sepolia
3. Select SygUSDC as token type.
4. Insert amount to be transfer as 12. 

Exp: The fee should be 1 and the amount to transfer should be 11. 
Act: The fee is 1 and the amount to be transferred is 10. 

![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/47b210fb-72a6-4380-b332-db47665bd3e8)

The issue is also found when using Source as Substrate and using a value in the lower bound 

![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/18bee854-0b3e-422b-90b0-a5f8e724dec6)

**Comment by LyonSsS** [comment]
This issue is visible only if the fee is percentage  ( lower and upper bound is fine) 
![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/0fad7047-f011-4496-ab60-1ab7c5e0c330)
![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/2e5f2df5-7d40-4b62-9305-2e88d0bea806)

**Comment by saadjhk** [comment]
@wainola why is this re opnened

**Comment by LyonSsS** [comment]
Retested on https://github.com/sygmaprotocol/sygma-widget/pull/196#pullrequestreview-2096177921
