### ISSUE TITLE
Create address to transfer component

### ISSUE THREAD

**Issue by wainola** [sygmaprotocol/sygma-widget#20]
## Implementation details

- by default it transfer to the same address that the wallet is connected, if destination chain is Evm based
- if destination chain is not Evm, toggle should not be rendered
- if toggle is active, input to add the address should be render
- we should apply styles defined in figma

## Acceptance Criteria

- if toggle is active, input must be displayed

**Comment by wainola** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/20?planning-poker) with Zenhub @FSM1 @wainola

**Comment by Lykhoyda** [comment]
@wainola is there a link for a design/figma?
