### ISSUE TITLE
SDK Manager Package: Substrate to EVM 

### ISSUE THREAD

**Issue by FSM1** [sygmaprotocol/sygma-widget#24]
## Implementation details

_Below are very high-level outlines of functionality, to be elaborated on once #6 is completed_

- Create logic that integrates SDK to this package.
- Create interfaces to call the relevant methods to perform a transfer.
- Package should return updates on the state of the transfer
- Provide means to hook to the events for the transfer and return updates to be displayed on the UI
- Provide unit test for it

## Testing details

- Upon connection to the provider and type of connection selected, one of the current asset transfers are created
- In isolation package is able to perform a Substrate to EVM fungible transfer

## Acceptance Criteria

- Test are passing on pipeline
- Using the package, we are able to make a Substrate to EVM transfer

**Comment by mpetrunic** [comment]
closing in favour of #93
