### ISSUE TITLE
Display fee

### ISSUE THREAD

**Issue by FSM1** [sygmaprotocol/sygma-widget#55]
## Story
As a bridge user, I want to know which fees I will be paying to bridge tokens.

## Background
The fee, as well as the token the fee is charged in should be displayed.
 
## Details
Screenshot is provisional
![image](https://github.com/sygmaprotocol/sygma-widget/assets/12774278/7ab32293-199d-409c-bd75-b04b356e94b2)

## Testing details
Test both Fixed and Percentage fee

## Acceptance criteria
Fee and FeeToken are displayed correctly.

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/55?planning-poker) with Zenhub @Lykhoyda @mpetrunic @wainola
