### ISSUE TITLE
filter source/dest network on network selection (inside WidgetController)

### ISSUE THREAD

**Issue by Lykhoyda** [sygmaprotocol/sygma-widget#71]
"filter source/dest network on network selection (inside WidgetController)"

Description
In sygma bridge, there may not be a route for every combination of source/destination networks. So when the user selects the source network, we should use sygma SDK to fetch available destination networks for this source network.

**Comment by wainola** [comment]
@Lykhoyda this issue implies an update to the current logic of the network selector? Also, should we create another issue in the sygma sdk repo?

**Comment by MakMuftic** [comment]
Already resolved
