### ISSUE TITLE
Create Widget Package 0.1.0

### ISSUE THREAD

**Issue by wainola** [sygmaprotocol/sygma-widget#8]
Widget package is the one that uses `sdk-manager` and `wallet-manager` package.

## Implementation details

- implement Widget package according to the spec and design
- Widget should receive props for customization and be able to change according to that, ie: providing different `primary` and `secondary` color as the one defined as base

**Comment by MakMuftic** [comment]
@MakMuftic add QA label

**Comment by mpetrunic** [comment]
Not sure why we havbe this considering that we have epic instead of this
