### ISSUE TITLE
Enable adding other web3 wallets

### ISSUE THREAD

**Issue by mpetrunic** [sygmaprotocol/sygma-widget#87]
## Implementation details
We should enable users to configure other wallets in Onboard library.

**Comment by saadjhk** [comment]
@mpetrunic @MakMuftic do we have a list of wallets that we would want to enable w.r.t priorities

**Comment by itsbobbyzzz168** [comment]
@saadjhk yes, list of wallets below:

EVM
1. metamask
2. Wallet Connect

Substrate
1. Polkadot.js
2. Talisman
3. Nova wallet

Overall order
1. Metamask
2. Polkadot.jjs
3. Talisman
4. Wallet connect/Nova

**Comment by mpetrunic** [comment]
Hey @saadjhk the goal is just enable user to pass https://github.com/blocknative/web3-onboard/blob/develop/packages/core/src/types.ts#L25 so they can install/enable any wallet supported by the library

**Comment by saadjhk** [comment]
@LyonSsS you would be able to verify this by providing your own wallet modules to `SygmaWidget` compoent

**Comment by itsbobbyzzz168** [comment]
@saadjhk hi ser, just for visibility if needing QA, just easier if you add label plus move it into QA and then will see it straight away <img width="1838" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnRlQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6314d6faceadada4006966f10ec1c2161a52600/Screenshot%202024-04-15%20at%2014.00.45.png" alt="Screenshot 2024-04-15 at 14.00.45.png" />

**Comment by saadjhk** [comment]
@itsbobbyzzz168 got it 👍🏻

**Comment by LyonSsS** [comment]
Tested on branch https://github.com/sygmaprotocol/sygma-widget  
I added a few wallets for test: 
<img width="1933" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3BsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8cbe094b64ecfa1bc123e0812bfc5f0ece95de1f/image.png" alt="image.png" />
All of them work but some of the integrations from "onboard" may require extra set-up. 
<img width="1532" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzFsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b830b574c3527112654675464aad620764af031/image.png" alt="image.png" />
 <img width="794" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0ZsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa78566a386a1c8b8c29af93626ebc723742b899/image.png" alt="image.png" />
<img width="862" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3hsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9edbe511baded42b102f0c291554de6f6e48c8a9/image.png" alt="image.png" />
<img width="1028" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzFsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a045dbe6fd505759ee68d343540dd45b8c931815/image.png" alt="image.png" />
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0JtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--078bd9144b08749eede613218e8ef735a91e0e6e/image.png" alt="image.png" />

Some fails: 
Ledger has some error issue reporting  
<img width="762" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd05tQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0015bf246091d4e1fe23c47d8648ac5b0d834495/image.png" alt="image.png" />

Trezor also has some issues: 
<img width="844" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1JtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--60d7e328213373bb0524ccb1f51476ba100e834c/image.png" alt="image.png" />

MEW also has some issues 
<img width="826" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1ZtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d8e132061b0213bb200e19ac41a498c4870b5d5/image.png" alt="image.png" />

The issues are related to the "onboard" libraries and are not subject to this ticket.  Closking this one
