### ISSUE TITLE
Fungible Transfer logic from Substrate chain

### ISSUE THREAD

**Issue by mpetrunic** [sygmaprotocol/sygma-widget#93]
## Implementation details

blocked by #74

**Comment by LyonSsS** [comment]
<img width="563" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFhEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61a15b214c685115eef7d360ffe3dfe1eed6a968/image.png" alt="image.png" />
