### ISSUE TITLE
Retry and loading for getting bridge routes

### ISSUE THREAD

**Issue by mpetrunic** [sygmaprotocol/sygma-widget#96]
## Implementation details
Without bridge routes, we cannot do much in the widget. I would  propose to retry infinitely and present full widget loading until we finally fetch routes (API has hardcoded values so only way this would fail if user doesn't have internet connection)

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/96?planning-poker) with Zenhub @Lykhoyda @mpetrunic @wainola

**Comment by mpetrunic** [comment]
closed via #136
