### ISSUE TITLE
Placeholder zero stays in input once you start typing amount

### ISSUE THREAD

**Issue by mpetrunic** [sygmaprotocol/sygma-widget#99]
## Expected Behavior
Zero is actual placeholder and not preselected input.

## Current Behavior
Placeholder zero stays in input once you start typing amount

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Version

Sygma commit (or docker tag):
sygma-solidity version:
sygma-substrate version:
Go version:

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-widget/99?planning-poker) with Zenhub @Lykhoyda @mpetrunic @wainola
